# -*- coding: utf-8 -*-
"""milestone3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1glifKcAy4O4qiMdQKENOOVmHaZYPxLzC
"""

import os
os.environ["STREAMLIT_SERVER_HEADLESS"] = "true"

import json
import torch
import torchvision
from torchvision import transforms
from PIL import Image
import numpy as np
import re
import streamlit as st

# -----------------------------
# Load Model (cached)
# -----------------------------
@st.cache_resource
def load_model():
    model = torchvision.models.detection.fasterrcnn_resnet50_fpn(weights="DEFAULT")
    model.eval()
    return model

model = load_model()

# -----------------------------
# Image Transform
# -----------------------------
transform = transforms.Compose([
    transforms.ToTensor(),
])

# -----------------------------
# Parse Dimensions
# -----------------------------
def parse_dimension(text):
    pattern = r"(\d+)\'(?:\s+(\d+)\")?\s*x\s*(\d+)\'(?:\s+(\d+)\")?"
    match = re.search(pattern, text)
    if match:
        ft1, inch1, ft2, inch2 = match.groups()
        width = float(ft1) + (float(inch1) if inch1 else 0) / 12.0
        height = float(ft2) + (float(inch2) if inch2 else 0) / 12.0
        return round(width, 2), round(height, 2)
    return None, None

# -----------------------------
# Orientation Detection
# -----------------------------
def detect_orientation(bbox):
    x1, y1, x2, y2 = bbox
    return "horizontal" if (x2 - x1) > (y2 - y1) else "vertical"

# -----------------------------
# Sample Room Data (mock)
# -----------------------------
room_texts = [
    ("BALCONY", "11' x 6'"),
    ("KITCHEN", "9' 4\" x 7' 3\""),
    ("LIVING", "16' 7\" x 17' 5\""),
    ("BEDROOM", "12' 6\" x 11' 6\""),
    ("BEDROOM", "12' 0\" x 9' 11\""),
    ("WALK-IN CLOSET", "6' 10\" x 5' 3\""),
    ("WALK-IN CLOSET", "6' 1\" x 5' 0\""),
    ("BATH", "12' 2\" x 5' 11\""),
    ("BEDROOM", "8' 1\" x 10' 9\""),
    ("BATH", "7' 7\" x 5' 10\""),
]

approximate_bboxes = [
    [50, 30, 180, 120],
    [200, 50, 350, 180],
    [400, 100, 650, 350],
    [50, 200, 250, 380],
    [280, 250, 450, 400],
    [480, 380, 600, 460],
    [620, 50, 700, 130],
    [50, 450, 200, 550],
    [250, 480, 400, 600],
    [450, 500, 580, 600],
]

# -----------------------------
# Generate JSON Output
# -----------------------------
def generate_json(image):
    img_tensor = transform(image).unsqueeze(0)

    with torch.no_grad():
        _ = model(img_tensor)  # inference (not used yet)

    floorplan = {
        "metadata": {
            "dimension_unit": "feet"
        },
        "properties": {
            "rooms": [],
            "orientation": "landscape" if image.width > image.height else "portrait"
        }
    }

    for i, (name, dim) in enumerate(room_texts):
        width, height = parse_dimension(dim)
        bbox = approximate_bboxes[i]

        floorplan["properties"]["rooms"].append({
            "name": name,
            "type": name.lower().replace(" ", "_"),
            "dimensions": {
                "width_ft": width,
                "height_ft": height,
                "area_sqft": round(width * height, 2) if width and height else None
            },
            "bounding_box_pixels": {
                "x1": bbox[0],
                "y1": bbox[1],
                "x2": bbox[2],
                "y2": bbox[3]
            },
            "orientation": detect_orientation(bbox),
            "connected_to": []
        })

    return floorplan

# -----------------------------
# STREAMLIT UI
# -----------------------------
st.title("🏠 Floor Plan Analyzer")

st.write("Upload a floor plan image (e.g., 6.jpeg)")

uploaded_file = st.file_uploader("Upload Image", type=["jpg", "jpeg", "png"])

if uploaded_file:
    image = Image.open(uploaded_file).convert("RGB")

    st.image(image, caption="Uploaded Image", use_column_width=True)

    with st.spinner("Analyzing..."):
        result = generate_json(image)

    st.subheader("📊 Output JSON")
    st.json(result)

    st.download_button(
        label="📥 Download JSON",
        data=json.dumps(result, indent=2),
        file_name="floorplan_output.json",
        mime="application/json"
    )
